# Generated by Django 5.1.6 on 2025-03-09 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
