# Generated by Django 5.1.6 on 2025-03-10 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request')),
                ('user', models.ForeignKey(db_column='customuser_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_request_assigned_users',
                'unique_together': {('request', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_requests', through='api.RequestAssignedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
