# Generated by Django 5.1.6 on 2025-03-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_requestassigneduser_alter_request_assigned_users'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_request_assigned_users;",
            reverse_sql="-- No reverse SQL provided as the table is dropped permanently."
        ),
    ]
